name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: Build image
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: Commit
      uses: pr-mpt/actions-commit-hash@v2
      with:
       commit: "${{ github.event.workflow_run.head_sha }}"
       prefix: ""
    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
            GIT_COMMIT=${{ steps.commit.outputs.long }}
            GIT_BRANCH=master
        push: true
        tags: kpajak/g2:latest

    
